// <auto-generated />
using Frags.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Frags.Database.Migrations
{
    [DbContext(typeof(RpgContext))]
    [Migration("20190317161250_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Frags.Core.Statistics.Statistic", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Statistic");
                });

            modelBuilder.Entity("Frags.Core.Statistics.StatisticValue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsProficient");

                    b.Property<double>("Proficiency");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.ToTable("StatisticValue");
                });

            modelBuilder.Entity("Frags.Database.Characters.CharacterDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("Experience");

                    b.Property<string>("Name");

                    b.Property<string>("Story");

                    b.Property<ulong>("UserIdentifier");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Frags.Database.Characters.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveCharacterId");

                    b.Property<ulong>("UserIdentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCharacterId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Frags.Database.Statistics.StatisticMapping", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CharacterDtoId");

                    b.Property<string>("StatisticId");

                    b.Property<string>("StatisticValueId");

                    b.HasKey("Id");

                    b.HasIndex("CharacterDtoId");

                    b.HasIndex("StatisticId");

                    b.HasIndex("StatisticValueId");

                    b.ToTable("StatisticMapping");
                });

            modelBuilder.Entity("Frags.Core.Statistics.Attribute", b =>
                {
                    b.HasBaseType("Frags.Core.Statistics.Statistic");

                    b.HasDiscriminator().HasValue("Attribute");
                });

            modelBuilder.Entity("Frags.Core.Statistics.Skill", b =>
                {
                    b.HasBaseType("Frags.Core.Statistics.Statistic");

                    b.Property<string>("AttributeId");

                    b.Property<int>("MinimumValue");

                    b.HasIndex("AttributeId");

                    b.HasDiscriminator().HasValue("Skill");
                });

            modelBuilder.Entity("Frags.Database.Characters.User", b =>
                {
                    b.HasOne("Frags.Database.Characters.CharacterDto", "ActiveCharacter")
                        .WithMany()
                        .HasForeignKey("ActiveCharacterId");
                });

            modelBuilder.Entity("Frags.Database.Statistics.StatisticMapping", b =>
                {
                    b.HasOne("Frags.Database.Characters.CharacterDto")
                        .WithMany("Statistics")
                        .HasForeignKey("CharacterDtoId");

                    b.HasOne("Frags.Core.Statistics.Statistic", "Statistic")
                        .WithMany()
                        .HasForeignKey("StatisticId");

                    b.HasOne("Frags.Core.Statistics.StatisticValue", "StatisticValue")
                        .WithMany()
                        .HasForeignKey("StatisticValueId");
                });

            modelBuilder.Entity("Frags.Core.Statistics.Skill", b =>
                {
                    b.HasOne("Frags.Core.Statistics.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId");
                });
#pragma warning restore 612, 618
        }
    }
}
